(function(){
 const KEY='sweetsonic_midi_applications', DEMO={id:'SS-MIDI-123456',name:'Demo Student',email:'demo@example.com',phone:'+91 90000 00000',experience:'Intermediate',schedule:'Weekend',goal:'Learn MIDI production and build a complete track.',status:'Enrolled',batch:'MIDI Academy — Weekend Batch',slot:'Saturday & Sunday · 10:00 AM–12:00 PM',faculty:'SweetSonic MIDI Faculty',startDate:'To be confirmed',submittedAt:new Date().toISOString()};
 const $=id=>document.getElementById(id); let student=null;
 function loadRecords(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){return[]}}
 function saveRecords(list){localStorage.setItem(KEY,JSON.stringify(list))}
 function findStudent(id,email){const r=loadRecords().find(x=>String(x.id).toLowerCase()===id.toLowerCase()&&String(x.email).toLowerCase()===email.toLowerCase()); return r||((id===DEMO.id&&email.toLowerCase()===DEMO.email)?DEMO:null)}
 function login(e){e.preventDefault();const r=findStudent($('loginId').value.trim(),$('loginEmail').value.trim());if(!r){$('loginError').textContent='We could not find that student record. Please check your Application ID and email.';return} if(!['Approved','Payment Pending','Paid','Enrolled'].includes(r.status||'')){ $('loginError').textContent='Your application is still under review. Student portal access will be enabled after approval.';return} student=r;sessionStorage.setItem('sweetsonic_student',JSON.stringify({id:r.id,email:r.email}));showDashboard()}
 function showDashboard(){if(!student)return;$('loginView').classList.add('hidden');$('dashboardView').classList.remove('hidden');$('studentName').textContent=student.name;$('portalId').textContent=student.id;$('portalStatus').textContent=student.status||'Approved';$('batchName').textContent=student.batch||'MIDI Academy — Weekend Batch';$('slotTime').textContent=student.slot||'Saturday & Sunday · 10:00 AM–12:00 PM';$('faculty').textContent=student.faculty||'SweetSonic MIDI Faculty';$('startDate').textContent=student.startDate||'To be confirmed';renderSessions();renderFiles()}
 function renderSessions(){let completed=Number(student.completedSessions||0);$('progressCount').textContent=completed;$('progressText').textContent=completed?`You have completed ${completed} of 24 sessions.`:'Your first session is waiting for you.';$('progressBar').style.width=Math.min(100,completed/24*100)+'%';const rows=[];for(let i=1;i<=24;i++){const done=i<=completed;rows.push(`<div class="session ${done?'done':''}"><div class="session-no">${String(i).padStart(2,'0')}</div><div><strong>Session ${i}</strong><small>${done?'Completed':'Upcoming · Session details will be shared by faculty'}</small></div><span class="status-pill">${done?'✓ Done':i===completed+1?'Next':'Planned'}</span></div>`)}$('sessionList').innerHTML=rows.join('')}
 function renderFiles(){const files=student.projects||[];$('fileList').innerHTML=files.length?files.map(f=>`<div class="file-row"><span>${f.name}</span><small>${f.size} · ${f.added}</small></div>`).join(''):'<p class="muted">No project files uploaded yet.</p>'}
 $('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem('sweetsonic_student');student=null;$('dashboardView').classList.add('hidden');$('loginView').classList.remove('hidden')});$('projectFiles').addEventListener('change',e=>{if(!student)return;const list=loadRecords();const rec=list.find(x=>x.id===student.id);if(!rec){student.projects=student.projects||[];Array.from(e.target.files).forEach(f=>student.projects.push({name:f.name,size:Math.round(f.size/1024)+' KB',added:new Date().toLocaleDateString()}));renderFiles();return}rec.projects=rec.projects||[];Array.from(e.target.files).forEach(f=>rec.projects.push({name:f.name,size:Math.round(f.size/1024)+' KB',added:new Date().toLocaleDateString()}));student=rec;saveRecords(list);renderFiles();e.target.value=''});
 try{const s=JSON.parse(sessionStorage.getItem('sweetsonic_student')||'null');if(s){const r=findStudent(s.id,s.email);if(r){student=r;showDashboard()}}}catch(_){ }
})();
